winget install WhatsApp -s msstore --accept-package-agreements
winget install -e --id Microsoft.VisualStudioCode
winget install -e --id Webroot.SecureAnywhere
winget install -e --id BleachBit.BleachBit
winget install -e --id sylikc.JPEGView
winget install -e --id Nvidia.GeForceNow
winget install -e --id Zoom.Zoom
winget install -e --id Google.Drive
winget install -e --id Valve.Steam
winget install -e --id Discord.Discord
winget install -e --id Anki.Anki
winget install -e --id Transmission.Transmission
winget install -e --id Mozilla.Firefox
winget install -e --id zhanglun.Lettura
winget install -e --id Surfshark.Surfshark
winget install -e --id Telegram.TelegramDesktop
winget install -e --id Spotify.Spotify
winget install -e --id Stellarium.Stellarium
winget install -e --id Squitch.Tess
winget install -e --id SomePythonThings.WingetUIStore
winget install -e --id OpenWhisperSystems.Signal
winget install -e --id Ombrelin.PandocGui
winget install -e --id Mozilla.Thunderbird
winget install -e --id MinhLoi.Midterm
winget install -e --id MacPaw.Encrypto
winget install -e --id LedgerHQ.LedgerLive
winget install -e --id Klocman.BulkCrapUninstaller
winget install -e --id KDE.Okular
winget install -e --id IObit.DriverBooster
winget install -e --id DataHammer.HammerPDF
